language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential zlib1g-dev libssl-dev libpng16-dev make

python:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - DISTUTILS_DEBUG=1 pip install -v -e .

script:
  - ldd -r bbi/cbbi*.so
  - pytest
